version: '2'

services:
    dal:
        build: ./
        volumes:
            - ./:/opt/project

    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=dal
            - MYSQL_USER=dal
            - MYSQL_PASSWORD=dev
        volumes:
            - ./tests/sql:/docker-entrypoint-initdb.d
