---
Graze\Dal\Dev\Customer:
    record: Graze\Dal\Dev\DoctrineOrm\Customer
    fields:
        id:
            mapsTo: id
        firstName:
            mapsTo: firstName
        lastName:
            mapsTo: lastName
    related:
        orders:
            type: oneToMany
            entity: Graze\Dal\Dev\Order
            foreignKey: customer_id
            collection: true
