---
Graze\Dal\Dev\Order:
    record: Graze\Dal\Dev\EloquentOrm\Order
    table: order
    timestamps: false
    fields:
        id:
            mapsTo: id
            type: int
        price:
            mapsTo: price
            type: float
    related:
        customer:
            type: manyToOne
            entity: Graze\Dal\Dev\Customer
            localKey: customer_id
        products:
            type: manyToMany
            entity: Graze\Dal\Dev\Product
            pivot: order_item
            localKey: order_id
            foreignKey: product_id
            collection: true

Graze\Dal\Dev\Product:
    record: Graze\Dal\Dev\EloquentOrm\Product
    table: product
    timestamps: false
    fields:
        id:
            mapsTo: id
            type: int
        name:
            mapsTo: name
            type: string
        price:
            mapsTo: price
            type: float
