---
Graze\Dal\Dev\DoctrineOrm\Customer:
    type: entity
    table: customer
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        first_name:
            type: string
        last_name:
            type: string
