---
Graze\Dal\Dev\Customer:
    table: customer
    fields:
        id:
            mapsTo: id
        firstName:
            mapsTo: first_name
        lastName:
            mapsTo: last_name
    related:
        orders:
            type: oneToMany
            entity: Graze\Dal\Dev\Order
            foreignKey: customer_id
            collection: true

Graze\Dal\Dev\Order:
    table: order
    fields:
        id:
            mapsTo: id
            type: int
        price:
            mapsTo: price
            type: float
    related:
        customer:
            type: manyToOne
            entity: Graze\Dal\Dev\Customer
            localKey: customer_id
        products:
            type: manyToMany
            entity: Graze\Dal\Dev\Product
            pivot: order_item
            localKey: order_id
            foreignKey: product_id
            collection: true

Graze\Dal\Dev\Product:
    table: product
    fields:
        id:
            mapsTo: id
            type: int
        name:
            mapsTo: name
            type: string
        price:
            mapsTo: price
            type: float
